# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Emeline Liu
tagline:             'Dabbles in things'
url:                 http://emelineliu.com
shorturl:			 emelineliu.com
paginate:            1
baseurl:             http://emelineliu.com

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Emeline Liu
  url:               https://twitter.com/eme______
  email:             emeline.liu@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              github.com/emelinemeline/emelinemeline.github.io
  
# For Disqus
disqusurl:			 http://emelineliu.com
  
# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
	
gems:
  - jekyll-sitemap
